### ISSUE TITLE
There's No Button or UI.

### ISSUE THREAD

**Issue by Bernardolima1234** [AstarLC4036/SFS-Multiplayer#1]
Hello AstarLC4036, i Have An Question For You, There's No UI or Button In Your Mod, Can You Fix it? That's The Issue.

**Comment by AstarLC4036** [comment]
What's your game version? UI works correctly on my PC.

**Comment by Bernardolima1234** [comment]
> What's your game version? UI works correctly on my PC.

1.5.10.2, why?

**Comment by AstarLC4036** [comment]
No UI in build scene? Have you installed mod correctly?
![image](https://github.com/AstarLC4036/SFS-Multiplayer/assets/126248249/7f242790-2994-492c-8f07-8904fd300a06)

**Comment by Bernardolima1234** [comment]
I Installed It But How Could I Add 11 Players In Multiplayer?

**Comment by AstarLC4036** [comment]
As you see, it's a pre-release, and I haven't enough time to update this mod, so please wait me complete the basic functions.
If you still have some questions, please communicate me on QQ(1975727002 - mail:1975727002@qq.com) or Discord(user name: alc4036)

**Comment by ExtraGamer1** [comment]
how do I make the mod work?

**Comment by andr769** [comment]
I have the same problem, had you found a solution for that?

**Comment by AstarLC4036** [comment]
You need to know this mod is not fully available to use.
